name: Notificar Update
on:
  workflow_dispatch:
  push:

jobs:
  notify:
    strategy:
      matrix:
        repo: ['Janosys-Log/Back-End', 'Janosys-Log/Front-End', 'Janosys-Log/.github']
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Disparar Evento
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.PAT_DISPATCH }}
          repository: ${{ matrix.repo }}
          event-type: update_submodule